name: CI for Converter

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the main and develop branches
    release:
        types: [published]

    push:
        branches:
        - main
        - develop

    pull_request:
        branches:
        - main

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow cointains only one single job
    unit-tests:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
          - uses: actions/checkout@v2
          - name: Set up Python 3.7
            uses: actions/setup-python@v2
            with:
                python-version: "3.7"

          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                python -m pip install -r requirements.txt
          - name: Test with unittest
            run:  python -m unittest unit_tests.py
